# Generated by Django 4.2.5 on 2023-10-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MalachiPollard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joshuamontgomery', models.EmailField(blank=True, max_length=100, unique=True)),
                ('robinhaney', models.CharField(max_length=95, null=True)),
                ('illianalindsay', models.ManyToManyField(to='core.default')),
            ],
        ),
    ]
