# Generated by Django 4.2.5 on 2023-10-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_malachipollard'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarrettCarrillo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imeldaramirez', models.CharField(blank=True, max_length=500, null=True)),
                ('samsonsweeney', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MalachiPollard',
        ),
    ]
